
export const FETCH_ALL_QUESTION = "FETCH_ALL_QUESTIONS"
export const ADD_NEW_QUESTIONS = "ADD_NEW_QUESTIONS"
export const LOGIN_USER = "LOGIN_USER"
export const ADD_USERS = "ADD_USERS"
export const ADD_USERS_QUESTIONS = "ADD_USERS_QUESTIONS"
export const GET_USERS_QUESIONS = "GET_USERS_QUESIONS"
export const GET_ALL_USERS_QUESIONS = "GET_ALL_USERS_QUESIONS"
export const FETCH_ERRORS = "FETCH_ERRORS"